@echo off

SET GRAMMAR_FILE=symbols.grm
SET GRAMMAR_TABLE_FILE=symbols.egt
SET LOG_FILE=symbols.log
SET HEADER_TEMPLATE_FILE=symbol-matcher-header-template.pgt
SET SOURCE_TEMPLATE_FILE=symbol-matcher-source-template.pgt
SET HEADER_FILE=SymbolMatcher.hpp
SET SOURCE_FILE=SymbolMatcher.cpp
SET PROGRAM_FILE_DESTINATION=..\src\Engine\TextParsers\SymbolMatcher

SET "GRAMMAR_TABLE_PATH=%~dp0gold-temp\%GRAMMAR_TABLE_FILE%"
SET "LOG_PATH=%~dp0gold-temp\%LOG_FILE%"
SET "HEADER_PATH=%~dp0\gold-temp\%HEADER_FILE%"
SET "SOURCE_PATH=%~dp0\gold-temp\%SOURCE_FILE%"

SET GOLD_BUILDER_TOOLS=c:\software\GOLD-Builder-5.2.0-Cmd\
SET GOLD_BUILD=%GOLD_BUILDER_TOOLS%GOLDbuild.exe
SET GOLD_PROGRAM=%GOLD_BUILDER_TOOLS%GOLDprog.exe

IF NOT EXIST gold-temp (
    MKDIR gold-temp
)

"%GOLD_BUILD%" +details "%GRAMMAR_FILE%" "%GRAMMAR_TABLE_PATH%" "%LOG_PATH%"
IF %ERRORLEVEL% NEQ 0 GOTO FAILED
"%GOLD_PROGRAM%" "%GRAMMAR_TABLE_PATH%" "%HEADER_TEMPLATE_FILE%" "%HEADER_PATH%"
IF %ERRORLEVEL% NEQ 0 GOTO FAILED
"%GOLD_PROGRAM%" "%GRAMMAR_TABLE_PATH%" "%SOURCE_TEMPLATE_FILE%" "%SOURCE_PATH%"
IF %ERRORLEVEL% NEQ 0 GOTO FAILED

py preprocess.py "%HEADER_PATH%"

COPY /B /Y /V "%HEADER_PATH%" "%PROGRAM_FILE_DESTINATION%\"
COPY /B /Y /V "%SOURCE_PATH%" "%PROGRAM_FILE_DESTINATION%\"

:FAILED
